server:
  port: 8080

spring:
  application:
    name: YueTiku-admin

  profiles:
    include: private                  # 引入私有配置文件

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: ${database.username}    # 数据库用户名
    password: ${database.password}    # 数据库密码

    #ai相关配置
  ai:
    dashscope:
      api-key: ${ai.api-key}
      chat:
        options:
          model: ${ai.model}

# MyBatis 配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml  # Mapper文件位置
  type-aliases-package: com.yuetiku.entity    # 实体类包路径

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true          # 下划线转驼峰
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    default-executor-type: simple
    default-statement-timeout: 25
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL日志输出到控制台
  global-config:
    db-config:
      id-type: auto                             # 主键策略：自动递增
      logic-delete-field: deleted              # 逻辑删除字段
      logic-delete-value: 1                    # 逻辑删除值
      logic-not-delete-value: 0                # 非删除值

# JWT配置 - 已修复密钥长度问题
jwt:
  secret: iFishSecretKeyForHS512AlgorithmMustBeAtLeast512BitsLongToEnsureSecurityAndCompliance2024
  expiration: 86400                             # 访问令牌过期时间（秒） - 24小时
  refresh-expiration: 604800                    # 刷新令牌过期时间（秒） - 7天

# 日志配置
logging:
  level:
    com.huashidai: debug              # 项目日志级别
    org.springframework.security: debug
    root: info                        # 根日志级别
    # SQL日志配置
    com.yuetiku.mapper: debug         # Mapper接口日志级别
    org.apache.ibatis: debug          # MyBatis日志级别
    java.sql.Connection: debug        # 数据库连接日志
    java.sql.Statement: debug         # SQL语句日志
    java.sql.PreparedStatement: debug # 预编译语句日志
    java.sql.ResultSet: debug         # 结果集日志